#if OSAllocatedUnfairLockUnsafeModify

#if canImport(Darwin)
import Darwin
#endif
import os

// Unsafe accessors that power the `_modify` accessor generated by
// `@OSAllocatedUnfairLock` when the `OSAllocatedUnfairLockUnsafeModify` package
// trait is enabled.
//
// `OSAllocatedUnfairLock<State>` is declared `@frozen` with exactly one stored
// property: `internal let __lock: ManagedBuffer<State, os_unfair_lock>`. Because
// the struct is frozen and contains a single class reference, `unsafeBitCast`-ing
// a value of type `OSAllocatedUnfairLock<State>` to
// `ManagedBuffer<State, os_unfair_lock>` recovers the same ManagedBuffer that the
// struct wraps internally. From there we can call `os_unfair_lock_lock` directly
// on the tail-allocated lock and hand out a pointer to the header-allocated state.
//
// This is intentionally gated behind a disabled-by-default package trait: it
// depends on implementation details of Apple's `os` framework that could change
// in a future Swift or OS release.
@available(macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0, *)
extension OSAllocatedUnfairLock {
    @inline(__always)
    public func _unsafeLock() -> UnsafeMutablePointer<State> {
        let buffer = unsafeBitCast(self, to: ManagedBuffer<State, os_unfair_lock>.self)
        return buffer.withUnsafeMutablePointers { header, lockPointer in
            os_unfair_lock_lock(lockPointer)
            return header
        }
    }

    @inline(__always)
    public func _unsafeUnlock() {
        let buffer = unsafeBitCast(self, to: ManagedBuffer<State, os_unfair_lock>.self)
        buffer.withUnsafeMutablePointerToElements { lockPointer in
            os_unfair_lock_unlock(lockPointer)
        }
    }
}

#endif
