#if canImport(os)

/// A named logging category selected per call site via the `category:`
/// argument of `#log`.
///
/// Declare categories once as static members, then reference them with
/// leading-dot syntax from any `@Loggable` type — the same pattern as
/// `Notification.Name`:
///
///     extension LogCategory {
///         static let network = LogCategory("network")
///         static let persistence = LogCategory("persistence")
///     }
///
///     @Loggable
///     struct SyncService {
///         func run() {
///             #log(.debug, category: .network, "request issued")
///         }
///     }
///
/// The receiving `logger(for:)` / `_osLog(for:)` accessors are generated by
/// `@Loggable` on every annotated type, backed by a process-wide cache keyed
/// by the subsystem/category pair.
public struct LogCategory: Hashable, Sendable {
    /// The category string passed to `os.Logger(subsystem:category:)`.
    public let name: String

    public init(_ name: String) {
        self.name = name
    }
}

#endif
