import SwiftDiagnostics
import SwiftSyntax
import SwiftSyntaxBuilder
import SwiftSyntaxMacros

/// `@RuntimeClassProxy("ClassName")` — peer macro on a protocol.
///
/// Generates `struct <ProtocolName>Implementation` conforming to the protocol,
/// with one signature-checked `@convention(c)` dispatch per requirement.
public enum RuntimeClassProxyMacro {}

let runtimeClassProxyMacroName = "@RuntimeClassProxy"

extension RuntimeClassProxyMacro: PeerMacro {
    public static func expansion(
        of node: AttributeSyntax,
        providingPeersOf declaration: some DeclSyntaxProtocol,
        in context: some MacroExpansionContext
    ) throws -> [DeclSyntax] {
        guard let protocolDeclaration = declaration.as(ProtocolDeclSyntax.self) else {
            context.emit(
                .error(
                    "proxyMustBeProtocol",
                    """
                    \(runtimeClassProxyMacroName) can only be applied to a protocol. \
                    Protocol requirements have no bodies, which is what lets the declaration stay plain Swift with nothing to stub out.
                    """
                ),
                at: node
            )
            return []
        }

        guard let className = parseProxyClassNameArgument(node, in: context) else {
            return []
        }

        let protocolName = protocolDeclaration.name.text
        let implementationTypeName = "\(protocolName)Implementation"

        let members = collectProxyMembers(in: protocolDeclaration, attribute: node, in: context)

        let requirementEntries = members
            .flatMap { $0.requirements }
            .map { requirement in
                ".init(selector: NSSelectorFromString(\(stringLiteral(requirement.selectorString))), typeEncoding: \(stringLiteral(requirement.typeEncoding)))"
            }
            .joined(separator: ",\n        ")

        let memberImplementations = members
            .map { $0.implementationText }
            .joined(separator: "\n\n    ")

        let requirementsArrayText = members.isEmpty ? "[]" : "[\n        \(requirementEntries),\n    ]"

        let generated: DeclSyntax = """
        /// Signature-checked caller for `\(raw: className)`, generated by `\(raw: runtimeClassProxyMacroName)`.
        struct \(raw: implementationTypeName): \(raw: protocolName) {
            /// Name of the Objective-C class this proxy calls into.
            static let runtimeClassName: String = \(literal: className)

            /// Every method this proxy dispatches, with the signature it assumes.
            static let methodRequirements: [ObjCRuntimeToolbox.RuntimeClassProxySupport.MethodRequirement] = \(raw: requirementsArrayText)

            /// Whether the class is present and every requirement still matches.
            /// Evaluated once; a mismatch is logged with both encodings.
            static let isSupported: Bool = ObjCRuntimeToolbox.RuntimeClassProxySupport.validate(
                className: runtimeClassName,
                requirements: methodRequirements,
                proxyTypeName: \(literal: implementationTypeName)
            )

            /// The object being called into.
            let host: AnyObject

            /// Wraps `host`, or fails when the class no longer matches what this
            /// proxy was generated against, or when `host` is not one of them.
            init?(_ host: AnyObject) {
                guard Self.isSupported else { return nil }
                guard ObjCRuntimeToolbox.RuntimeClassProxySupport.isInstance(host, ofClassNamed: Self.runtimeClassName) else { return nil }
                self.host = host
            }

            \(raw: memberImplementations)
        }
        """

        return [generated]
    }
}

// MARK: - Argument Parsing

private func parseProxyClassNameArgument(
    _ node: AttributeSyntax,
    in context: some MacroExpansionContext
) -> String? {
    guard let argumentList = node.arguments?.as(LabeledExprListSyntax.self),
          let firstArgument = argumentList.first
    else {
        context.emit(
            .error(
                "missingProxyClassName",
                "\(runtimeClassProxyMacroName) requires the target class name, e.g. \(runtimeClassProxyMacroName)(\"NSStatusBarWindow\")."
            ),
            at: node
        )
        return nil
    }

    guard let className = extractStringLiteral(from: firstArgument.expression), !className.isEmpty else {
        context.emit(
            .error(
                "proxyClassNameMustBeStringLiteral",
                "\(runtimeClassProxyMacroName): the class name must be a non-empty string literal — it is resolved with objc_getClass."
            ),
            at: firstArgument.expression
        )
        return nil
    }

    return className
}

// MARK: - Member Collection

private struct ProxyRequirement {
    let selectorString: String
    let typeEncoding: String
}

private struct ProxyMember {
    let requirements: [ProxyRequirement]
    let implementationText: String
}

private func collectProxyMembers(
    in protocolDeclaration: ProtocolDeclSyntax,
    attribute: AttributeSyntax,
    in context: some MacroExpansionContext
) -> [ProxyMember] {
    var collected: [ProxyMember] = []

    for member in protocolDeclaration.memberBlock.members {
        if let functionDeclaration = member.decl.as(FunctionDeclSyntax.self) {
            if let proxyMember = buildMethodMember(functionDeclaration, in: context) {
                collected.append(proxyMember)
            }
            continue
        }

        if let variableDeclaration = member.decl.as(VariableDeclSyntax.self) {
            if let proxyMember = buildPropertyMember(variableDeclaration, in: context) {
                collected.append(proxyMember)
            }
            continue
        }

        context.emit(
            .warning(
                "unsupportedProxyMember",
                "\(runtimeClassProxyMacroName): only methods and properties can be proxied. This requirement is not implemented by the generated type, so the protocol will not be satisfied."
            ),
            at: member.decl
        )
    }

    if collected.isEmpty {
        context.emit(
            .warning(
                "emptyProxyProtocol",
                "\(runtimeClassProxyMacroName): the protocol declares nothing to proxy. The generated type will validate an empty requirement list and dispatch nothing."
            ),
            at: attribute
        )
    }

    return collected
}

// MARK: - Methods

private func buildMethodMember(
    _ functionDeclaration: FunctionDeclSyntax,
    in context: some MacroExpansionContext
) -> ProxyMember? {
    let canProceed = diagnoseUnsupportedFunctionShape(
        functionDeclaration,
        in: context,
        overrideMarker: nil,
        macroName: runtimeClassProxyMacroName
    )
    guard canProceed else { return nil }

    let shape = FunctionShape(from: functionDeclaration)

    // A returning proxy method must be optional — see the macro documentation.
    if let returnTypeSyntax = shape.returnTypeSyntax,
       !isOptionalTypeSyntax(returnTypeSyntax)
    {
        context.emit(
            .error(
                "proxyReturnMustBeOptional",
                """
                \(runtimeClassProxyMacroName): a returning proxy method must declare an optional return type. \
                Dispatch into a class resolved at runtime can fail, and there is no honest default to invent — write '\(returnTypeSyntax.trimmedDescription)?' and handle nil (or '?? someDefault') at the call site.
                """
            ),
            at: returnTypeSyntax
        )
        return nil
    }

    let selectorString = shape.selectorString()
    let typeEncoding = ObjCTypeEncoding.methodEncoding(
        returnTypeText: shape.returnTypeText,
        parameterTypeTexts: shape.parameters.map { $0.typeText }
    )

    let declaredParameterList = shape.parameters.map { parameter in
        let label = parameter.externalLabel == parameter.internalName
            ? parameter.externalLabel
            : "\(parameter.externalLabel) \(parameter.internalName)"
        return "\(label): \(parameter.typeText)"
    }.joined(separator: ", ")

    let returnClauseText = shape.returnTypeText.map { " -> \($0)" } ?? ""
    let bodyText = buildDispatchBody(
        selectorString: selectorString,
        parameterTypeTexts: shape.parameters.map { $0.typeText },
        argumentExpressions: shape.parameters.map { $0.internalName },
        declaredReturnTypeText: shape.returnTypeText
    )

    let implementationText = """
    func \(shape.baseName)(\(declaredParameterList))\(returnClauseText) {
    \(bodyText)
        }
    """

    return ProxyMember(
        requirements: [ProxyRequirement(selectorString: selectorString, typeEncoding: typeEncoding)],
        implementationText: implementationText
    )
}

// MARK: - Properties

private func buildPropertyMember(
    _ variableDeclaration: VariableDeclSyntax,
    in context: some MacroExpansionContext
) -> ProxyMember? {
    guard let binding = variableDeclaration.bindings.first,
          let identifierPattern = binding.pattern.as(IdentifierPatternSyntax.self),
          let typeAnnotation = binding.typeAnnotation
    else {
        context.emit(
            .error(
                "proxyPropertyNeedsExplicitType",
                "\(runtimeClassProxyMacroName): a proxied property needs an explicit type annotation."
            ),
            at: variableDeclaration
        )
        return nil
    }

    let propertyName = identifierPattern.identifier.text
    let propertyTypeSyntax = typeAnnotation.type
    let propertyTypeText = propertyTypeSyntax.trimmedDescription

    guard isOptionalTypeSyntax(propertyTypeSyntax) else {
        context.emit(
            .error(
                "proxyPropertyMustBeOptional",
                """
                \(runtimeClassProxyMacroName): a proxied property must be optional. \
                Reading a class resolved at runtime can fail, and there is no honest default to invent — write '\(propertyTypeText)?' and handle nil at the call site.
                """
            ),
            at: propertyTypeSyntax
        )
        return nil
    }

    let hasSetter = binding.accessorBlock.map(accessorBlockDeclaresSetter) ?? false

    let getterSelectorString = propertyName
    let getterEncoding = ObjCTypeEncoding.methodEncoding(
        returnTypeText: propertyTypeText,
        parameterTypeTexts: []
    )

    var requirements = [ProxyRequirement(selectorString: getterSelectorString, typeEncoding: getterEncoding)]

    let implementationText: String
    if hasSetter {
        let getterBody = buildDispatchBody(
            selectorString: getterSelectorString,
            parameterTypeTexts: [],
            argumentExpressions: [],
            declaredReturnTypeText: propertyTypeText,
            indentation: "            "
        )
        let setterSelectorString = setterSelectorName(forPropertyNamed: propertyName)
        let setterEncoding = ObjCTypeEncoding.methodEncoding(
            returnTypeText: nil,
            parameterTypeTexts: [propertyTypeText]
        )
        requirements.append(ProxyRequirement(selectorString: setterSelectorString, typeEncoding: setterEncoding))

        let setterBody = buildDispatchBody(
            selectorString: setterSelectorString,
            parameterTypeTexts: [propertyTypeText],
            argumentExpressions: ["newValue"],
            declaredReturnTypeText: nil,
            indentation: "            "
        )

        implementationText = """
        var \(propertyName): \(propertyTypeText) {
                get {
        \(getterBody)
                }
                nonmutating set {
        \(setterBody)
                }
            }
        """
    } else {
        let getterBody = buildDispatchBody(
            selectorString: getterSelectorString,
            parameterTypeTexts: [],
            argumentExpressions: [],
            declaredReturnTypeText: propertyTypeText
        )
        implementationText = """
        var \(propertyName): \(propertyTypeText) {
        \(getterBody)
            }
        """
    }

    return ProxyMember(requirements: requirements, implementationText: implementationText)
}

private func accessorBlockDeclaresSetter(_ accessorBlock: AccessorBlockSyntax) -> Bool {
    guard case .accessors(let accessorList) = accessorBlock.accessors else { return false }
    return accessorList.contains { $0.accessorSpecifier.tokenKind == .keyword(.set) }
}

/// `fileURL` → `setFileURL:`, `isHidden` → `setHidden:` — matching how the
/// Objective-C runtime names a synthesised setter, including the `is` prefix
/// rule for boolean properties.
private func setterSelectorName(forPropertyNamed propertyName: String) -> String {
    if propertyName.count > 2,
       propertyName.hasPrefix("is"),
       let thirdCharacter = propertyName.dropFirst(2).first,
       thirdCharacter.isUppercase
    {
        return "set\(propertyName.dropFirst(2)):"
    }
    let capitalizedFirst = propertyName.prefix(1).uppercased()
    return "set\(capitalizedFirst)\(propertyName.dropFirst()):"
}

// MARK: - Dispatch Emission

/// The shared body: resolve the implementation off the host's real class, cast
/// it to the signature the encoding was derived from, and call it.
private func buildDispatchBody(
    selectorString: String,
    parameterTypeTexts: [String],
    argumentExpressions: [String],
    declaredReturnTypeText: String?,
    indentation: String = "        "
) -> String {
    let selectorExpression = "NSSelectorFromString(\(stringLiteral(selectorString)))"
    let isVoidReturn = declaredReturnTypeText == nil
    let failureReturn = isVoidReturn ? "return" : "return nil"

    var conventionParameterTypes = ["AnyObject", "Selector"]
    conventionParameterTypes.append(contentsOf: parameterTypeTexts)

    var callArguments = ["host", "selector"]
    callArguments.append(contentsOf: argumentExpressions)
    let callArgumentList = callArguments.joined(separator: ", ")

    let lines: [String]
    if let declaredReturnTypeText {
        let unwrappedReturnTypeText = stripOneOptionalLayer(from: declaredReturnTypeText)
        let returnsObject = ObjCTypeEncoding.encoding(forTypeText: unwrappedReturnTypeText) == "@"

        if returnsObject {
            // Ownership follows Objective-C's method families rather than
            // whatever the call site guesses.
            let consume = selectorReturnsRetainedValue(selectorString) ? "takeRetainedValue" : "takeUnretainedValue"
            let conventionSignature = "@convention(c) (\(conventionParameterTypes.joined(separator: ", "))) -> Unmanaged<AnyObject>?"
            let castSuffix = unwrappedReturnTypeText == "AnyObject" ? "" : " as? \(unwrappedReturnTypeText)"
            lines = [
                "let selector = \(selectorExpression)",
                "guard let implementation = ObjCRuntimeToolbox.RuntimeClassProxySupport.implementation(of: selector, on: host) else { \(failureReturn) }",
                "let dispatchFunction = unsafeBitCast(implementation, to: (\(conventionSignature)).self)",
                "return dispatchFunction(\(callArgumentList))?.\(consume)()\(castSuffix)",
            ]
        } else {
            let conventionSignature = "@convention(c) (\(conventionParameterTypes.joined(separator: ", "))) -> \(unwrappedReturnTypeText)"
            lines = [
                "let selector = \(selectorExpression)",
                "guard let implementation = ObjCRuntimeToolbox.RuntimeClassProxySupport.implementation(of: selector, on: host) else { \(failureReturn) }",
                "let dispatchFunction = unsafeBitCast(implementation, to: (\(conventionSignature)).self)",
                "return dispatchFunction(\(callArgumentList))",
            ]
        }
    } else {
        let conventionSignature = "@convention(c) (\(conventionParameterTypes.joined(separator: ", "))) -> Void"
        lines = [
            "let selector = \(selectorExpression)",
            "guard let implementation = ObjCRuntimeToolbox.RuntimeClassProxySupport.implementation(of: selector, on: host) else { \(failureReturn) }",
            "let dispatchFunction = unsafeBitCast(implementation, to: (\(conventionSignature)).self)",
            "dispatchFunction(\(callArgumentList))",
        ]
    }

    return lines.map { indentation + $0 }.joined(separator: "\n")
}

/// Objective-C's method families: these four return +1 and the caller owns the
/// result. Everything else returns +0.
private func selectorReturnsRetainedValue(_ selectorString: String) -> Bool {
    for family in ["alloc", "new", "copy", "mutableCopy"] {
        guard selectorString.hasPrefix(family) else { continue }
        // `newspaper` is not the `new` family; the character after the prefix
        // must not be a lowercase letter.
        let remainder = selectorString.dropFirst(family.count)
        if let next = remainder.first, next.isLowercase { continue }
        return true
    }
    return false
}

// MARK: - Optional Handling

func isOptionalTypeSyntax(_ typeSyntax: TypeSyntax) -> Bool {
    if typeSyntax.is(OptionalTypeSyntax.self) { return true }
    if typeSyntax.is(ImplicitlyUnwrappedOptionalTypeSyntax.self) { return true }
    let text = typeSyntax.trimmedDescription
    return text.hasPrefix("Optional<") && text.hasSuffix(">")
}

func stripOneOptionalLayer(from typeText: String) -> String {
    var result = typeText.trimmedWhitespace
    if result.hasSuffix("?") || result.hasSuffix("!") {
        result = String(result.dropLast())
    } else if result.hasPrefix("Optional<"), result.hasSuffix(">") {
        result = String(result.dropFirst("Optional<".count).dropLast())
    }
    result = result.trimmedWhitespace
    // `(Foo)?` unwraps to `(Foo)`; drop redundant parentheses so the emitted
    // convention signature reads normally.
    while result.hasPrefix("("), result.hasSuffix(")") {
        let inner = String(result.dropFirst().dropLast()).trimmedWhitespace
        if inner.containsSubstring(",") || inner.containsSubstring("->") { break }
        result = inner
    }
    return result
}
